/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class MathLibrary */

#ifndef _Included_MathLibrary
#define _Included_MathLibrary
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     MathLibrary
 * Method:    add
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_MathLibrary_add
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
